language: node_js
node_js:
  - "6"
script:
  - npm run check:src
  - npm run build
  - npm run check:examples
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
  - examples/simple/node_modules
